// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Storage struct {
	ID        int32
	Value     int64
	UpdatedAt pgtype.Timestamp
}
