// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	// Get current storage value
	// Parameters: none
	// Returns: Single storage row
	GetStorage(ctx context.Context) (Storage, error)
	// Create or update storage value (singleton row)
	// Parameters: value
	// Returns: Updated storage row
	SetStorage(ctx context.Context, value int64) (Storage, error)
}

var _ Querier = (*Queries)(nil)
