// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: storage.sql

package db

import (
	"context"
)

const getStorage = `-- name: GetStorage :one
SELECT id, value, updated_at
FROM storage
WHERE id = 1
LIMIT 1
`

// Get current storage value
// Parameters: none
// Returns: Single storage row
func (q *Queries) GetStorage(ctx context.Context) (Storage, error) {
	row := q.db.QueryRow(ctx, getStorage)
	var i Storage
	err := row.Scan(&i.ID, &i.Value, &i.UpdatedAt)
	return i, err
}

const setStorage = `-- name: SetStorage :one
INSERT INTO storage (id, value, updated_at)
VALUES (1, $1, NOW())
ON CONFLICT (id)
DO UPDATE SET
    value = EXCLUDED.value,
    updated_at = NOW()
RETURNING id, value, updated_at
`

// Create or update storage value (singleton row)
// Parameters: value
// Returns: Updated storage row
func (q *Queries) SetStorage(ctx context.Context, value int64) (Storage, error) {
	row := q.db.QueryRow(ctx, setStorage, value)
	var i Storage
	err := row.Scan(&i.ID, &i.Value, &i.UpdatedAt)
	return i, err
}
